import argparse

def ParseArgs():
    parser = argparse.ArgumentParser(description='Model Parameters')
    parser.add_argument('--lr', default=1e-3, type=float, help='Learning rate')
    parser.add_argument('--batch', default=4096, type=int, help='Batch size')
    parser.add_argument('--leaky', default=0.5, type=float, help='Slope of the LeakyReLU activation')
    parser.add_argument('--tstBat', default=64, type=int, help='Number of users in a testing batch')
    parser.add_argument('--epoch', default=1000, type=int, help='Maximum number of epochs')
    parser.add_argument('--patience', default=4, type=int, help='Patience for early stopping')
    parser.add_argument('--decay', default=1e-4, type=float, help='Weight decay rate (L2 regularization)')
    parser.add_argument('--save_path', default='tem1', help='File name to save the model and training records')
    parser.add_argument('--latdim', default=32, type=int, help='Embedding size (latent dimension)')
    parser.add_argument('--hyperNum', default=128, type=int, help='Number of hyperedges')
    parser.add_argument('--gnn_layer', default=2, type=int, help='Number of GNN layers')
    parser.add_argument('--load_model', default=None, help='Name of the model file to load')
    parser.add_argument('--topk', default=20, type=int, help='Top-K value for evaluation metrics')
    parser.add_argument('--att_head', default=8, type=int, help='Number of attention heads')
    parser.add_argument('--keepRate', default=0.5, type=float, help='Ratio of edges to keep after sampling')
    parser.add_argument('--temp', default=0.2, type=float, help='Temperature parameter for softmax smoothing')
    parser.add_argument('--block_num', default=2, type=int, help='Number of hops in GCN processing')
    parser.add_argument('--mult', default=1, type=float, help='Multiplication factor for scoring')
    parser.add_argument('--data', default='yelp', type=str, help='Name of the dataset')
    parser.add_argument('--tstEpoch', default=2, type=int, help='Number of epochs between evaluations during training')
    parser.add_argument('--gpu', default='0', type=str, help='GPU device ID to use')
    parser.add_argument('--edgeSampRate', default=20, type=int, help='Attention sampling size (number of edges)')
    parser.add_argument('--dropout', default=0.1, type=float, help='Dropout ratio in the transformer layers')
    parser.add_argument('--num_head', default=8, type=int, help='Number of heads in multi-head attention')
    parser.add_argument('--trans_layer', default=3, type=int, help='Number of transformer layers')
    parser.add_argument('--num_runs', default=5, type=int, help='Number of runs for averaging the final results')
    parser.add_argument('--do_search', default=True, type=bool, help='Whether to perform hyperparameter search')
    parser.add_argument('--search_runs', default=1, type=int, help='Number of runs for each hyperparameter combination')
    parser.add_argument('--background', default=False, type=bool, help='Whether to run the script in background mode')
    parser.add_argument('--generate_cmd', default=False, type=bool, help='Whether to generate a background execution command')
    return parser.parse_args()

args = ParseArgs()
